on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
    paths:
      - migrations/**

env:
  CARGO_TERM_COLOR: always
  SQLX_VERSION: 0.7.3
  SQLX_FEATURES: "rustls,postgres"

  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: password
  DATABASE_HOST: 127.0.0.1
  DATABASE_NAME: pokemon_graphql
  DATABASE_PORT: 5432

jobs:
  test:
    name: Migration Test
    runs-on: ubuntu-latest
    env:
      ENV: test
      DATABASE_URL: postgres://${{ env.DATABASE_USERNAME }}:${{ env.DATABASE_PASSWORD }}@${{ env.DATABASE_HOST }}:${{ env.DATABASE_PORT }}/${{ env.DATABASE_NAME }}
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
        ports:
          - 5432:5432
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          key: sqlx-${{ env.SQLX_VERSION }}
      - name: Install sqlx-cli
        run:
          cargo install sqlx-cli
          --version=${{ env.SQLX_VERSION }}
          --features ${{ env.SQLX_FEATURES }}
          --no-default-features
          --locked
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Migrate database HEAD
        run: |
          sudo apt-get install libpq-dev -y
          SKIP_DOCKER=true SKIP_ENV=true ./scripts/init_db.sh
      - uses: actions/checkout@v4
      - name: Migrate Current Change
        run: sqlx migrate run